-- users
CREATE TABLE IF NOT EXISTS users (
	id			BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name		VARCHAR(255) NOT NULL,
	email		VARCHAR(512) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (id),
	CONSTRAINT uq_users_email UNIQUE (email)
);

-- requests
CREATE TABLE IF NOT EXISTS requests (
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	description		TEXT NOT NULL,
	requestor_id	BIGINT NOT NULL,
	created			TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_requests PRIMARY KEY (id),
	CONSTRAINT fk_requests_requestor_id FOREIGN KEY (requestor_id) REFERENCES users(id)
);

-- items
CREATE TABLE IF NOT EXISTS items (
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name			VARCHAR(255) NOT NULL,
	description		TEXT NOT NULL,
	is_available	BOOLEAN NOT NULL,
	owner_id		BIGINT NOT NULL,
	request_id		BIGINT,
	CONSTRAINT pk_items PRIMARY KEY (id),
	CONSTRAINT fk_items_owner_id FOREIGN KEY (owner_id) REFERENCES users(id),
	CONSTRAINT fk_items_request_id FOREIGN KEY (request_id) REFERENCES requests(id)
);

-- bookings
CREATE TABLE IF NOT EXISTS bookings (
	id			BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	start_date	TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	end_date	TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	item_id		BIGINT NOT NULL,
	booker_id	BIGINT NOT NULL,
	status		VARCHAR(16) NOT NULL,
	CONSTRAINT pk_bookings PRIMARY KEY (id),
	CONSTRAINT fk_bookings_item_id FOREIGN KEY (item_id) REFERENCES items(id),
	CONSTRAINT fk_bookings_booker_id FOREIGN KEY (booker_id) REFERENCES users(id)
);

-- comments
CREATE TABLE IF NOT EXISTS comments (
	id			BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	text		TEXT NOT NULL,
	item_id		BIGINT NOT NULL,
	author_id	BIGINT NOT NULL,
	CONSTRAINT pk_comments PRIMARY KEY (id),
	CONSTRAINT fk_comments_item_id FOREIGN KEY (item_id) REFERENCES items(id),
	CONSTRAINT fk_comments_author_id FOREIGN KEY (author_id) REFERENCES users(id)
);